name: Smoke

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ensure Playwright cache dir exists
        run: mkdir -p ~/.cache/ms-playwright

      - name: Cache Playwright browsers
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-pw-${{ hashFiles('playwright.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-pw-

      - name: Ensure package.json exists (workspace only)
        run: |
          if [ ! -f package.json ]; then
            npm init -y >/dev/null 2>&1
          fi

      - name: Install Playwright test runner (local)
        run: npm i -D @playwright/test@1.45.3

      - name: Install OS deps & Chromium (ALWAYS; uses cache if present)
        run: |
          npx -y @playwright/test@1.45.3 install-deps
          npx -y @playwright/test@1.45.3 install chromium

      - name: Run smoke tests (Chromium headless)
        run: npx -y @playwright/test@1.45.3 test

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            test-results/**
            playwright-report/**
